spring.application.name=Social-profile

JWT.SECRET=${JWT_SECRET}
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${DATABASE_NAME}

cloudflare.r2.access-key=${R2_ACCESS_KEY}
cloudflare.r2.secret-key=${R2_SECRET_KEY}
cloudflare.r2.account-id=${R2_ACCOUNT_ID}
cloudflare.r2.bucket-name=${R2_BUCKET}
cloudflare.r2.public-base-url=${R2_PUBLIC_BASE_URL}
cloudflare.r2.endpoint=${R2_ENDPOINT}


logging.level.org.springframework.web=INFO

spring.servlet.multipart.max-file-size=50MB

spring.servlet.multipart.max-request-size=50MB


app.cors.allowed-origins=*

