spring.application.name=Social-profile

JWT.SECRET=${JWT_SECRET}
spring.data.mongodb.uri=${MONGO_URI}

cloudflare.r2.bucket-name=${R2_BUCKET}
cloudflare.r2.access-key=${R2_ACCESS_KEY}
cloudflare.r2.secret-key=${R2_SECRET_KEY}
cloudflare.r2.public-base-url=${R2_PUBLIC_BASE_URL}
cloudflare.r2.endpoint=${R2_ENDPOINT}
